### ISSUE TITLE
Pack error for BLUI plugin

### ISSUE THREAD

**Issue by luofxgucas** [getnamo/BLUI-Unreal#10]
Version: v3.2.5 for UE 4.19

This plugin works well in UEditor, but there is an error when  I pack a project with this plugin.

The error is that:

doespackageexist failed: '/blui/bluiworldwidgetactorexample' is not a standard unreal filename 

How to fix this error? Looking forward to your reply. Thanks!

Have a nice day!

**Comment by npcbx** [comment]
1.open the UEeditor
2.move  All Assets in plugins content to your project's content,
3.package again

**Comment by xzessmedia** [comment]
i have the same problem and was already trying the recommended way -> copying missing assets in project folder. even after removing the plugins content and copying them to project content folder i get in any package result 

`[2019.04.29-10.43.55:213][ 93]LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/BLUI/BluiWorldWidgetActorExample' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/DungeonArchitect/', '/MeshTool/', '/PrefabTool/', '/Paper2D/', '/CryptoKeys/', '/MeshEditor/', '/DatasmithContent/', '/VariantManagerContent/', '/MediaCompositing/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
[2019.04.29-10.43.55:213][ 93]LogStreaming: Error: Couldn't find file for package /BLUI/BluiWorldWidgetActorExample requested by async loading code. NameToLoad: /BLUI/BluiWorldWidgetActorExample`
