### ISSUE TITLE
How to resize blui canvas ?

### ISSUE THREAD

**Issue by GMAGD** [getnamo/BLUI-Unreal#15]
by resizing blui widget ,mouse cursor not working  i can't  click on input fields it's look like the browser widget was been shifted  idk.

more info : i don't won't blui widget to be full screen i won't it to specific position 
HELP !!!

**Comment by getnamo** [comment]
If you use the _BluiWorldWidgetActorExample_, inside its begin play

![image](https://user-images.githubusercontent.com/542365/58385760-301ebf00-7faa-11e9-808b-4058c257cdea.png)

 you can see that the _widget draw size_ is passed into _Init Blu Eye_

![image](https://user-images.githubusercontent.com/542365/58385765-4b89ca00-7faa-11e9-8c35-140c7325b9a5.png)

which sets the correct draw size in the Blu Eye instance.

![image](https://user-images.githubusercontent.com/542365/58385756-19786800-7faa-11e9-81e2-ceda360f5632.png)

![image](https://user-images.githubusercontent.com/542365/58385770-652b1180-7faa-11e9-9132-4da0d1eee1fe.png)


If both the world widget draw size and the blu eye draw size are set correctly, your rendering will be aligned.

**Comment by GMAGD** [comment]
hey Thank you so mush

**Comment by GMAGD** [comment]
i want the widget to be in the middle of screen is that possible

**Comment by GMAGD** [comment]
@getnamo hey what about webrtc and access to mice  how can i do that ? it only work with apprtc 
but in speech to text doesn't work thank in advance

**Comment by getnamo** [comment]
Moving the widget should be done by the owner of the widget, just move the actor if it's a world widget. WebRTC I believe requires a newer chromium build see https://github.com/getnamo/BLUI/issues/11. I'm probably not going to update chromium for a while (not enough time), but the general instructions to do that can be found here https://github.com/AaronShea/BluBrowser

**Comment by GMAGD** [comment]
![image](https://user-images.githubusercontent.com/21009210/58703440-ff26fb80-83a8-11e9-980a-aa6069a186f3.png)

**Comment by GMAGD** [comment]
if i click up it show cursor

**Comment by GMAGD** [comment]
![image](https://user-images.githubusercontent.com/21009210/58703502-31385d80-83a9-11e9-8d5b-aeda0a204001.png)

**Comment by GMAGD** [comment]
Plz Help

**Comment by GMAGD** [comment]
i'm only using widget to viewport not the actor

**Comment by getnamo** [comment]
https://api.unrealengine.com/INT/BlueprintAPI/UserInterface/Viewport/SetAlignmentinViewport/index.html

**Comment by GMAGD** [comment]
hey bro thx for your help i tried what you give me but no chance :(   
the problem is that blu render the widget according to the size given but i translate the widget with y + 200 i lose  click on my inputs field  but if i click on top as i showed you in picture it work so what's wrong plz help
