### ISSUE TITLE
Testing pdf and blui

### ISSUE THREAD

**Issue by fpibbs** [getnamo/BLUI-Unreal#17]
Hi all,
I'd love to understand if it will be possible to render pdf files directly inserted into project, locally or via URL.
Thanks!

**Comment by getnamo** [comment]
You should be able to do that with something like https://github.com/mozilla/pdf.js which renders pdf in javascript

**Comment by fpibbs** [comment]
Already implemented PDF.js, however CEF has specific protection in opening js and local files (locked). So, I recompiled Unreal source code with plugins enabled and now it's working. 
Getnamo blui is rendering them and works, but for the moment it has problems with scrolling (see precedent posts) and doesn't compile.
