### ISSUE TITLE
Slider doesnt work

### ISSUE THREAD

**Issue by DruidEdu** [getnamo/BLUI-Unreal#18]
Slider doesn't work when I slide it,I use Unreal4.22

**Comment by getnamo** [comment]
What slider? might need to elaborate on what exactly you mean

**Comment by DruidEdu** [comment]
I'm sorry for my describe.When I slide down a slider like a Youtube page, the page doesn't move.

**Comment by hege104** [comment]
@getnamo 
The slider on the right side of the webpage cannot be slid. How to solve this problem

**Comment by getnamo** [comment]
Try using TriggerMouseWheel for scrolling a page (https://github.com/getnamo/BLUI/blob/master/Source/Blu/Public/BluEye.h#L128)

**Comment by getnamo** [comment]
Closing due to age
