### ISSUE TITLE
the keyboard inputs doe's not work in the ExampleHUD widget .. any solution ?

### ISSUE THREAD

**Issue by ghost** [getnamo/BLUI-Unreal#20]
i followed all the instructions in the wiki the mouse move and the click is working but when it comes to writing ... it's doe's not accept the keyboard input

**Comment by oivio** [comment]
Be patient. I did just recreate old Demo for ue4.22 where you will have a few samples showing all interactions. Also, I will make a Video showcasing and also I will try to explain how things do work.

**Comment by immersiveboard** [comment]
Hey ! really nice work :) is it possible to get a ue4.26 demo :) because blu eye is not working and i don't know how to do :) thank u so much. B.R

**Comment by getnamo** [comment]
Closing due to age
