### ISSUE TITLE
Replace BluiBrowser with WebBrowser

### ISSUE THREAD

**Issue by lvhuming** [getnamo/BLUI-Unreal#26]
Replace BluiBrowser with WebBrowser

**Comment by oivio** [comment]
? BluiBrowser is independent. If you want something depended have a look at Marketplace for HTML Menus.

**Comment by getnamo** [comment]
I'm assuming you mean https://github.com/EpicGames/UnrealEngine/blob/master/Engine/Source/Runtime/WebBrowser/WebBrowser.Build.cs.

This fork will likely not adapt such a change so we can maintain control over the CEF version used. I recommend implementing it in a separate fork. Also keep in mind that platforms outside of Win/Linux/Mac do not use CEF in the WebBrowser module but their native browsers with the limitations they have.

**Comment by lvhuming** [comment]
> I'm assuming you mean https://github.com/EpicGames/UnrealEngine/blob/master/Engine/Source/Runtime/WebBrowser/WebBrowser.Build.cs.
> 
> This fork will likely not adapt such a change so we can maintain control over the CEF version used. I recommend implementing it in a separate fork. Also keep in mind that platforms outside of Win/Linux/Mac do not use CEF in the WebBrowser module but instead use their native browsers with the limitations they have.

I want to use ITextInputMethodSystem。
but simage not suppot ITextInputMethodSystem。

WebBrowser：
ITextInputMethodSystem* const TextInputMethodSystem = FSlateApplication::Get().GetTextInputMethodSystem();
WebBrowserWidget->BindInputMethodSystem(TextInputMethodSystem);
