### ISSUE TITLE
CEF update

### ISSUE THREAD

**Issue by oivio** [getnamo/BLUI-Unreal#29]
I did try to make TensorFlow sites work with this plugin but, without success. It might be a problem with old CEF libs. So my solution was to update CEF. 

Iv found this:

Official Chromium Embedded Framework: https://bitbucket.org/chromiumembedded/cef/src/master/
Automated Builds - http://opensource.spotify.com/cefbuilds/index.html

and also I did try to follow the instruction on how to update this plugin but......to many errors with VS2017. Python code is outdate it also I do not know PY lang at all. 

Is there an easier solution to get that update working?

**Comment by GMAGD** [comment]
u got **LNK** errors caused by the **linker** maybe because u have old windows sdk 8.1 u need to update to windows sdk 10 to make it work i guess 

[https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk](url)

**Comment by GMAGD** [comment]
hey @oivio don't use python just download last cef and blubrowser and copy it to cefsample and build 
u will get some errors u need to fix

**Comment by oivio** [comment]
> hey @oivio don't use python just download last cef and blubrowser and copy it to cefsample and build
> u will get some errors u need to fix

Currently, I am really busy. So I did postpone that update. Probably will try it in some spear time but, thank you for a hint.

**Comment by getnamo** [comment]
CEF hase now been updated to 80.0.3987.132 in the latest release: https://github.com/getnamo/BLUI/releases/tag/3.7.0

**Comment by JaccoGoris** [comment]
Thank you @getnamo ! this is amazing
