### ISSUE TITLE
No input on the UMG widget?

### ISSUE THREAD

**Issue by fbnz156** [getnamo/BLUI-Unreal#30]
It seems like the UMG widget is completely lacking in any input method (mouse, keyboard, or otherwise). Looking at the blueprint, I can't find anything indicating that it's supposed to be there. Was this intentional or an oversight?

I feel like input should be a basic feature,

**Comment by oivio** [comment]
I do agree. In the beginning, I did have the exact same problem. But after a few days of digging iv made it working. You can have a look at demos that I did create: https://www.youtube.com/watch?v=iCAe7dyy9dw links for download ver 4.22 and 4.23 are in the description. Then have a look at BP "BIUICharacter" and you will see that in my demo I do use widget interaction. But for the full-screen widget I did use function overrides. To see it open "FullScreenWidgetUI" it is Widget Folder.
