### ISSUE TITLE
Everything is blank in a packaged demo

### ISSUE THREAD

**Issue by pcjjdy** [getnamo/BLUI-Unreal#31]
I download your demo for 4.22 and package it. When I open the BLUI.exe, I find every module seems invalid. Including BLUI 1-10 and the logo in the top-left of screen is blank. I am not sure if I did something wrong and my package setting is default. Can you help me?
![微信图片_20191119113617](https://user-images.githubusercontent.com/8905213/69114620-ea5a3380-0ac0-11ea-817f-d357a6c078fb.png)

**Comment by oivio** [comment]
hi. This demo is a bit dated. Can you try this demo: 

https://www.youtube.com/watch?v=iCAe7dyy9dw  

Download: 

4.22:  https://mega.nz/#!gbwgxYqY!CnCA_9WZOxMFjbPWw-uUVU52f2tSlgu3ygSaEalecDA
4.23: https://mega.nz/#!8LpS2aDL!tqir1LK0VxakJ0Xo5-zn4iSIbQ4XRThB24_LdMJNFtw

**Comment by pcjjdy** [comment]
> hi. This demo is a bit dated. Can you try this demo:
> 
> https://www.youtube.com/watch?v=iCAe7dyy9dw
> 
> Download:
> 
> 4.22: https://mega.nz/#!gbwgxYqY!CnCA_9WZOxMFjbPWw-uUVU52f2tSlgu3ygSaEalecDA
> 4.23: https://mega.nz/#!8LpS2aDL!tqir1LK0VxakJ0Xo5-zn4iSIbQ4XRThB24_LdMJNFtw

I download it and packeted immediately but failed. Here is the log file.
[BLUI.log](https://github.com/getnamo/BLUI/files/3862339/BLUI.log)

**Comment by oivio** [comment]
> I download it and packeted immediately but failed. Here is the log file.
> [BLUI.log](https://github.com/getnamo/BLUI/files/3862339/BLUI.log)

Thank you. There is a small mistake that has been made by me. I did set the wrong "HTML" directory in project settings. There is a simple fix for that:

Just go to:

Project Settings-> Packaging->Click in Packaging tab to Show Advanced ->In "Additional Non-Assets Directories to Package" change "HTML" to "../HTML" 

Basicly "HTML" folder contains offline website files that you can use or load.

**Comment by pcjjdy** [comment]
> > I download it and packeted immediately but failed. Here is the log file.
> > [BLUI.log](https://github.com/getnamo/BLUI/files/3862339/BLUI.log)
> 
> Thank you. There is a small mistake that has been made by me. I did set the wrong "HTML" directory in project settings. There is a simple fix for that:
> 
> Just go to:
> 
> Project Settings-> Packaging->Click in Packaging tab to Show Advanced ->In "Additional Non-Assets Directories to Package" change "HTML" to "../HTML"
> 
> Basicly "HTML" folder contains offline website files that you can use or load.

Well, I can package successfully. I can't wait to detect anything different with PIE environment.  I find that the local path modules may get some problems. I mean the "Simple JS with CSS Buttons Example" and "HUD Example". I can't see their effects in development package. I am not sure if this is associate with the errors here:
![image](https://user-images.githubusercontent.com/8905213/69128795-0a511d80-0ae8-11ea-99a8-bae859365fe8.png)

**Comment by getnamo** [comment]
Closing due to age
