### ISSUE TITLE
Is scroll not working, or am I just calling it incorrectly?

### ISSUE THREAD

**Issue by TheRealSamGamgee** [getnamo/BLUI-Unreal#33]
Has anyone tried to use TriggerMouseWheel to scroll in a file? I could have sworn I had it working, but that might have been on 4.20, I can't remember.

**Comment by TheRealSamGamgee** [comment]
I'm using 4.23 now

**Comment by getnamo** [comment]
have you tried some of the tips in this thread: https://github.com/getnamo/BLUI/issues/14?

**Comment by ThomasBoute** [comment]
I know it's an old post, but this works for me on 4.26
![image](https://user-images.githubusercontent.com/43601556/120495873-5fe4d680-c3bd-11eb-8451-181503e77a28.png)
