### ISSUE TITLE
Can support Linux?

### ISSUE THREAD

**Issue by lvhuming** [getnamo/BLUI-Unreal#40]
Can support Linux?

**Comment by getnamo** [comment]
In theory, yes. I personally don't plan on compiling CEF chromium for that platform though, it will require someone else to build it and make a pull request.

**Comment by lvhuming** [comment]
I compiled the binary file under Linux, and there was an error when linking the file

error：undefined reference to `std::_rb_tree_decrement(std::_Rb_tree_node_base const*)
libcef_dll_wrapper.a(transfer_util.cc.o): in function `std::pair<std::_Rb_tree_iterator<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > >, bool> std::_Rb_tree<CefStringBase<CefStringTraitsUTF16>, std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> >, std::_Select1st<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > >, std::less<CefStringBase<CefStringTraitsUTF16> >, std::allocator<std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > > >::_M_emplace_unique<std::pair<CefStringBase<CefStringTraitsUTF16>, CefStringBase<CefStringTraitsUTF16> > >(std::pair<CefStringBase<CefStringTraitsUTF16>, CefStringBase<CefStringTraitsUTF16> >&&)':
1>  transfer_util.cc:(.text._ZNSt8_Rb_treeI13CefStringBaseI20CefStringTraitsUTF16ESt4pairIKS2_S2_ESt10_Select1stIS5_ESt4lessIS2_ESaIS5_EE17_M_emplace_uniqueIJS3_IS2_S2_EEEES3_ISt17_Rb_tree_iteratorIS5_EbEDpOT_[_ZNSt8_Rb_treeI13CefStringBaseI20CefStringTraitsUTF16ESt4pairIKS2_S2_ESt10_Select1stIS5_ESt4lessIS2_ESaIS5_EE17_M_emplace_uniqueIJS3_IS2_S2_EEEES3_ISt17_Rb_tree_iteratorIS5_EbEDpOT_]+0x16c): undefined reference to `std::_Rb_tree_decrement(std::_Rb_tree_node_base*)'
1>clang++ : error : linker command failed with exit code 1 (use -v to see invocation)

**Comment by lvhuming** [comment]
How should I compile the required files? Thank you

**Comment by lvhuming** [comment]
> In theory, yes, but in practice it requires rebuilding CEF for linux. I personally don't plan on compiling CEF/chromium for that platform though, so it will require someone else to build it and make a pull request.
> 
> See https://github.com/getnamo/BluBrowser/ for some hints on how to do this.

How should I compile the required files? Thank you

**Comment by getnamo** [comment]
Closed as duplicate in favor of https://github.com/getnamo/BLUI-Unreal/issues/69
