### ISSUE TITLE
How to use in C++ project?

### ISSUE THREAD

**Issue by aaron1a12** [getnamo/BLUI-Unreal#46]
Hi, I'm using the plugin in a C++ ue4 project but when I build in VS I get the following errors:

`ERROR: Could not find definition for module 'BluLoader', (referenced via default plugins -> BLUI.uplugin)`

When I include the source code I get a missing "ModuleManager.h" error. How do I build with this plugin added to the project? Should I add it to the engine instead?

**Comment by aaron1a12** [comment]
When pasting into project "Plugins" folder in VS2015:
">P:/TestGame/UE4/Plugins/BLUI/Source/BluLoader/Private/BluLoaderPrivatePCH.h(6): fatal error C1083: Cannot open include file: 'ModuleManager.h': No such file or directory"

**Comment by getnamo** [comment]
I believe since 4.24 you need to prepend **Modules**/ModuleManager.h for includes. See e.g. https://docs.unrealengine.com/en-US/API/Runtime/Core/Modules/FModuleManager/index.html for guidance on includes for that module

**Comment by aaron1a12** [comment]
Ok.. I also had to prepend "Windows" to many other includes:
`#include "Windows/WindowsHWrapper.h"`

**Comment by malcriado3d** [comment]
and...also have to prepend:
#include "Windows/HideWindowsPlatformAtomics.h"
#include "Windows/HideWindowsPlatformTypes.h"
