### ISSUE TITLE
Youtube live videos aren't playing

### ISSUE THREAD

**Issue by 6r0m** [getnamo/BLUI-Unreal#49]
error with message your browser unsupported. 
Is it hard to support live translations?

**Comment by getnamo** [comment]
Not sure, haven't tried live videos, might want to look at the log to see if any error crops up. It might be a codec issue (h264 is not compiled in chromium by default due to licensing), or some permission that still isn't granted.

**Comment by 6r0m** [comment]
Thanks for your answer! Looks like a codec problem, I have achieved youtube live through vlc plugin with unreal media player with stream source. If you have time, please try to compile with proprietary codecs, very interesting in results.

**Comment by masterkyodai** [comment]
I also have this issue. Unfortunately I'm too dumb to get the VLC plugin compiled. Any chance for supporting live streams (Twitch, Youtube, etc) in a future release?

For example I would like to stream this live TV station:

https://www.youtube.com/watch?v=coYw-eVU0Ks

**Comment by 6r0m** [comment]
I have solved this in comment section [here](url=https://answers.unrealengine.com/questions/966292/view.html)

**Comment by masterkyodai** [comment]
As I said - I am unable to compile the VLC plugin. I always get the dreaded "Project can not be compiled. Try rebuilding from source manually" error and for plugins there's no "Right click to generate Visual studio files" trick. So I simply can't get VLC plugin compiled. Tried on 4.24 and 4.26. If someone got a compiled 4.26 VLC then let me know.

**Comment by getnamo** [comment]
Closing due to age
