### ISSUE TITLE
BLUI Does not work On IOS 

### ISSUE THREAD

**Issue by lijiuyi0000** [getnamo/BLUI-Unreal#5]
Hello, getname, i use blui plugin, can work in windows ,when i package to ios ,it does not work. why?

**Comment by lijiuyi0000** [comment]
and Can i get All files under the plugins/BLUI/ThirdParty/cef/Mac/Shipping ?﻿

**Comment by getnamo** [comment]
iOS likely has a pretty complicated setup for plugins with dependencies. I only prebuild and maintain the windows platform, but you can get CEF library builds here: http://opensource.spotify.com/cefbuilds/index.html

As you can see neither iOS nor Android are built by default, you'd need to compile from source (https://bitbucket.org/chromiumembedded/cef/src)

**Comment by VladimirTaytor** [comment]
Hello, sorry for bumping so old issue, just want to share info. I was thinking to add BLUI into my project, but as it uses CEF, on iOS it will not work, because Apple allows using only their UIWebView(Safari). Chrome on iOS is just "Safari with another UI":) Anyway, thanks for your work!

**Comment by getnamo** [comment]
Recommended to use https://docs.unrealengine.com/5.1/en-US/API/Runtime/WebBrowser/ for iOS/Android platform support
