### ISSUE TITLE
Does not work if DefaultBuildSettings is not set to BuildSettingsVersion.V2

### ISSUE THREAD

**Issue by sorab2142** [getnamo/BLUI-Unreal#52]
I am upgrading a project from UE 4.22 to 4.25 and if I dont use the following:
DefaultBuildSettings = BuildSettingsVersion.V2;
because I would need to update all legacy paths (#includes)

Your plugin throws a compile error:
BLUI\Source\Blu\Public\RenderHandler.h(3): fatal error C1083: Cannot open include file: 'CEFInclude.h': No such file or directory

Why is this file in a Private directory? And how do I compile without that flag on?

**Comment by getnamo** [comment]
That setting should just force IWYU with stricter settings. I'm not sure if moving it to public solves it, but that change seems harmless so I pushed it here: https://github.com/getnamo/BLUI/commit/94e04b331f3144665de6a544976d256867d0932c

While I do have build settings v2 enabled, I might not be using the class in C++ which could cause the build error. Let me know if the minor change resolves it.

**Comment by sorab2142** [comment]
Thanks @getnamo that fixes it.
