### ISSUE TITLE
Compiler error C2027 at UE4.26 dev-rendering branch

### ISSUE THREAD

**Issue by happyend85** [getnamo/BLUI-Unreal#55]
Trying to use the plugin in dev-rendering branch (UE 4.26). Every time I try to compile the plugin, the error 2027 appears. Whyever the compiler says, that it couldn't find the definition for Texture2DRecource, also when I include the .h file. 
Does anyone have any hints on how to compile the plugin for UE 4.26?

**Comment by happyend85** [comment]
Anyone any idea?

**Comment by getnamo** [comment]
You might need to post the exact error message/line number and context to give clues as to what would need to change for 4.26. Usually plugin gets updated ~ 1 week after new engine release otherwise.

**Comment by happyend85** [comment]
Hi,
Error msg is: 
C2027: Using of undefined type "FTexture2DRecource" in BlueEye.cpp Line 178

**Comment by getnamo** [comment]
Change ```FTexture2DResource``` to ```FTextureResource```

**Comment by happyend85** [comment]
Tried it. But then I receive more errors, that FTextureResource couldn't be converted to FTexture2DRecource. Will wait until you release the plugin for UE 4.26.Dou you have a plan when you will do that?

**Comment by getnamo** [comment]
I generally sweep all my plugins ~ 1 week after the first non-preview engine version gets released. Sometimes it takes a bit longer especially if there are big changes.
