### ISSUE TITLE
Click/hover on the website not working (UE 4.25)

### ISSUE THREAD

**Issue by TestDemoLS** [getnamo/BLUI-Unreal#59]
I'm using v4.0.0 for UE 4.25 and when adding the "InteractableBluiWidgetActor" the click/hover on the website (youtube.com) is not working, it doesn't seem to be receiving any inputs at all.

Based on the documentation this blueprint should work out of the box, not sure if anything changed that requires modifications for the blueprints to work.

Thanks

**Comment by Ty-lerCox** [comment]
![image](https://user-images.githubusercontent.com/6323925/120056921-3fa7c700-c00d-11eb-850c-95d34dbf66e8.png)
I am having the same issue. This is how I am initializing the widget.

**Comment by getnamo** [comment]
Try examples and latest version. Closing due to age
