### ISSUE TITLE
Cookies are automatically deleted due to CEF bug. How to update plugin with newer CEF version?

### ISSUE THREAD

**Issue by vle07** [getnamo/BLUI-Unreal#60]
I think the CEF version used for this plugin has a bug that automatically deletes cookies, so cookies can't persist between sessions: [https://bitbucket.org/chromiumembedded/cef/issues/2890/all-the-cookies-are-deleted-automatically](https://bitbucket.org/chromiumembedded/cef/issues/2890/all-the-cookies-are-deleted-automatically)

Are there any plans to update the CEF version? I can also try updating it myself, but it seems really involved. So far, I've download a recent CEF build from: https://cef-builds.spotifycdn.com/index.html. Then I've replaced the cefsimple test project with the blubrowser project here: https://github.com/getnamo/blubrowser. Using CMake, I generate the project files. I'm a little unclear about the /MT or /MD outputs. Do I need to build the solution twice, once with each configuration to generate all of the necessary files? If you have any tips or resources for updating the code to get the solution to build (and what to do after that), it'd be appreciated. This is a great plugin and is much easier to extend than the default UE4 web browser. Thanks!

Edit: Seems like cookies work in a packaged project when setting "persist_session_cookies" and "persist_user_preferences" to true. Not sure why it doesn't work when using the UE4 editor.

**Comment by getnamo** [comment]
Interesting bug. I do occasionally re-sync CEF builds, but it won't be more often than ~ once every 6months. If you need an update sooner, https://github.com/getnamo/blubrowser is the correct repo to do it. You do need to change some settings in the .sln manually the /MT checkbox can be found under blu_ue4_process project  _Configuration Properties-> C/C++->Code Generation-> Runtime Library_

I usually do a build all and then copy the required libs in Win/lib and all the updated process under Win/shipping. Essentially ensure _Plugins\BLUI\ThirdParty\cef\Win_ is up to date with newest cef build and update your headers and it should work.

**Comment by getnamo** [comment]
Closing in favor of #81
