### ISSUE TITLE
I cannot click the slider to slide the page

### ISSUE THREAD

**Issue by hege104** [getnamo/BLUI-Unreal#61]
@getnamo 
When I click on the slider of the slider page, it doesn't work. What's wrong with this

**Comment by getnamo** [comment]
Might need a click and hold command. Can you select text in the page with the same method?

**Comment by hege104** [comment]
I can't achieve click and hold you said to select text, what should I set，Or what should I do?

**Comment by getnamo** [comment]
Try https://github.com/getnamo/BLUI/blob/master/Source/Blu/Public/BluEye.h#L108 and then later https://github.com/getnamo/BLUI/blob/master/Source/Blu/Public/BluEye.h#L116

**Comment by hege104** [comment]
I tried TiggerLeftMouseDown，TriggerLeftMouseUp，TriggerLeftClick，TriggerMouseWheel and it didn't work when I held down the slider and it didn't work when I selected text
![texture](https://user-images.githubusercontent.com/43395105/114801972-67c9c680-9dcf-11eb-9994-1fc199eb550a.png)

>

**Comment by ThomasBoute** [comment]
Hi Jan! 

Thank you for the great work you did with this plugin! It helped me a lot to display pdf files and to access to protected files from APIs. It seems I have the same problem, I can't use the right slider to view all the pages of the pdf displayed in the browser. I thought Set InputModeUI would solve that like the Webbrowser frim UE, but no. Any idea?

Keep up the great work and have a nice day!

**Comment by ThomasBoute** [comment]
I found it by using the triggers!
