### ISSUE TITLE
After successful packaging, EXE failed to run

### ISSUE THREAD

**Issue by fistpan** [getnamo/BLUI-Unreal#73]
After I test the windows project with the 4.27 and 5.0 experience versions, when I open the EXE, I will be prompted to plug in "bluI" failed to load because module bluiloader could be found please ensure that the plugin is properly installed otherwise consider disabling the plugin for this project

What is the problem and how to solve it
thank

**Comment by getnamo** [comment]
If you're packaging a blueprint project you need to convert it from blueprint only to hybrid so it compiles the plugin for release config. See e.g. https://github.com/getnamo/socketio-client-ue4#github

**Comment by getnamo** [comment]
Closing due to age, re-open if converting didn't fix it
