### ISSUE TITLE
UE5 packaging failure problem

### ISSUE THREAD

**Issue by fistpan** [getnamo/BLUI-Unreal#74]
UATHelper: 打包 (Windows): LogWindows: Error: begin: stack for UAT
UATHelper: 打包 (Windows): LogWindows: Error: === Critical error: ===
UATHelper: 打包 (Windows): LogWindows: Error:
UATHelper: 打包 (Windows): LogWindows: Error: Fatal error!
UATHelper: 打包 (Windows): LogWindows: Error:
UATHelper: 打包 (Windows): LogWindows: Error: Unhandled Exception: 0x80000003
UATHelper: 打包 (Windows): LogWindows: Error:
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf59823e5 libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf7111471 libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf66ac99e libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf43ced9f libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf61a7b16 libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf5752f63 libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf5753a7a libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf57537e5 libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf607198d libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf592c522 libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf592c09f libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffcf39a129b libcef.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffd050019b8 UnrealEditor-Blu.dll!CefInitialize() []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffd04ff5efb UnrealEditor-Blu.dll!FBlu::StartupModule() [D:\UE5GkcPluginDemo\Bluitext1\Plugins\BLUI-Unreal\Source\Blu\Private\Blu.cpp:44]
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffd4a70e96d UnrealEditor-Core.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffd7137aaf6 UnrealEditor-Projects.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffd7138de4a UnrealEditor-Projects.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffd7137a8b0 UnrealEditor-Projects.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ff679ed537d UnrealEditor-Cmd.exe!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ff679ed866e UnrealEditor-Cmd.exe!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ff679ed0bbd UnrealEditor-Cmd.exe!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ff679ed0e8a UnrealEditor-Cmd.exe!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ff679ed3c4d UnrealEditor-Cmd.exe!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ff679ee5534 UnrealEditor-Cmd.exe!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ff679ee7836 UnrealEditor-Cmd.exe!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffdb55f7034 KERNEL32.DLL!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error: [Callstack] 0x00007ffdb59c2651 ntdll.dll!UnknownFunction []
UATHelper: 打包 (Windows): LogWindows: Error:
UATHelper: 打包 (Windows): LogWindows: Error: end: stack for UAT
PackagingResults: Error: begin: stack for UAT
PackagingResults: Error: === Critical error: ===
PackagingResults: Error: Fatal error!
PackagingResults: Error: Unhandled Exception: 0x80000003
PackagingResults: Error: [Callstack] 0x00007ffcf59823e5 libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf7111471 libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf66ac99e libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf43ced9f libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf61a7b16 libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf5752f63 libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf5753a7a libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf57537e5 libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf607198d libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf592c522 libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf592c09f libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffcf39a129b libcef.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffd050019b8 UnrealEditor-Blu.dll!CefInitialize() []
PackagingResults: Error: [Callstack] 0x00007ffd04ff5efb UnrealEditor-Blu.dll!FBlu::StartupModule() [D:\UE5GkcPluginDemo\Bluitext1\Plugins\BLUI-Unreal\Source\Blu\Private\Blu.cpp:44]
PackagingResults: Error: [Callstack] 0x00007ffd4a70e96d UnrealEditor-Core.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffd7137aaf6 UnrealEditor-Projects.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffd7138de4a UnrealEditor-Projects.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffd7137a8b0 UnrealEditor-Projects.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff679ed537d UnrealEditor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff679ed866e UnrealEditor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff679ed0bbd UnrealEditor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff679ed0e8a UnrealEditor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff679ed3c4d UnrealEditor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff679ee5534 UnrealEditor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff679ee7836 UnrealEditor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffdb55f7034 KERNEL32.DLL!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffdb59c2651 ntdll.dll!UnknownFunction []
PackagingResults: Error: end: stack for UAT
UATHelper: 打包 (Windows): ERROR: Cook failed.
PackagingResults: Error: Cook failed.
PackagingResults: Error: Unknown Cook Failure

**Comment by getnamo** [comment]
Have you tried the latest release?

https://github.com/getnamo/BLUI-Unreal/releases/tag/v4.4.0

**Comment by saidmoya12** [comment]
Crash with UE5.0.1 and web browser plugin enabled.

**Comment by getnamo** [comment]
Known issue can't have both enabled, see https://github.com/getnamo/BLUI-Unreal/issues/23
