### ISSUE TITLE
Crash at start on UE5.0.3 (Bridge incompatibility issue)

### ISSUE THREAD

**Issue by Tobe2d** [getnamo/BLUI-Unreal#77]
It was working fine on EU5 Early Access, and now on UE 5.0.3 it crash once I start the project with the error below:

LoginId:154a576940f8a07fd773f3ae828fc571
EpicAccountId:d787ad54491446f0ad9cba758a62f077

Assertion failed: bSuccess [File:D:\build\++UE5\Sync\Engine\Source\Runtime\WebBrowser\Private\WebBrowserSingleton.cpp] [Line: 397]

UnrealEditor_WebBrowser
UnrealEditor_WebBrowser
UnrealEditor_Bridge
UnrealEditor_Bridge
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_LevelEditor
UnrealEditor_LevelEditor
UnrealEditor_LevelEditor
UnrealEditor_LevelEditor
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_MainFrame
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by getnamo** [comment]
Disable the built-in webbrowser/bridge plugin. They are incompatible with BLUI.

**Comment by Tobe2d** [comment]
Thanks @getnamo 
I disable bridge and it fixed the crash.

Hope to see update fixing this as we will need bridge as well.

**Comment by getnamo** [comment]
Related to: https://github.com/getnamo/BLUI-Unreal/issues/80. Closing in favor of that issue
