### ISSUE TITLE
HTML5 target platform for 4.23

### ISSUE THREAD

**Issue by Zohan11** [getnamo/BLUI-Unreal#78]
is there a ninja way to make it work on a HTML5 target platform?

**Comment by getnamo** [comment]
Not likely, you'd need to compile CEF to wasm I think and then figure out the way to load that separate wasm built browser correctly within html (how do the offscreen rendering hooks work in that context?). You'd likely have better luck trying to write an HTML wrapper to work inside the target browser that samples the screen of e.g. a hidden element and passes that image data back to unreal somehow. Either way sounds like a super complex task.
