### ISSUE TITLE
Reverse premultiplied alpha

### ISSUE THREAD

**Issue by eanticev** [getnamo/BLUI-Unreal#8]
(posting issue here since this repo seems to be the most up to date)

Skia colors in CEF will have premultiplied alpha so a pixel with value (255,255,255,0.5) will actually render out as (125,125,125,0.5) in the final texture. This causes whites to appear as grey when layered over as transparent in UE4.

The solution is simple: re-multiply the color value with 1/alpha in a shader. Here's how:

1. Make `MaterialInstance` public like so
```c
/** Material instance that has final rendered result */
UPROPERTY(BlueprintReadOnly)
UMaterialInstanceDynamic* MaterialInstance;
```

2. Provide a material with the domain `User Interface` in the Content examples for the plugin with the following simple graph:

![image](https://user-images.githubusercontent.com/723013/34505787-3fd4b594-efdc-11e7-811a-4fc45e1a6338.png)

3. Set that as the default material and use a material brush to render out the final image in the content example `BluiWidget`:

![image](https://user-images.githubusercontent.com/723013/34505809-7c136a00-efdc-11e7-848d-935e25671299.png)

**Comment by eanticev** [comment]
I should note that this is only relevant for TRANSPARENT renders of the widget.

**Comment by getnamo** [comment]
Seems like you have a fix, consider making a pull request and i'll merge it.

**Comment by getnamo** [comment]
Closed due to age
