### ISSUE TITLE
UE5.1 Unable to capture user input

### ISSUE THREAD

**Issue by nickmaleki** [getnamo/BLUI-Unreal#85]
I am able to display websites and local html using the latest version of the plugin, but I am unable to get any user input from keyboard or mouse, even from InteractableBluiWidgetActor. Anyone having a similar issue?

**Comment by getnamo** [comment]
Have you tried the earlier example projects(ones shown by oivio https://github.com/getnamo/BLUI-Unreal#demo-project? Api should be largely the same to that era plugin

**Comment by nickmaleki** [comment]
> Have you tried the earlier example projects(ones shown by oivio https://github.com/getnamo/BLUI-Unreal#demo-project? Api should be largely the same to that era plugin

Yes
