### ISSUE TITLE
Can we deploy apps with this plugin, or this is only useful for displaying UI in browser?

### ISSUE THREAD

**Issue by RBoira97** [getnamo/BLUI-Unreal#96]
Hi to all,

I'd like to know if we using this is possible to deploy an app to browser. Maybe I misunderstood the main funcionality but gave me some hope to to some things on web.

**Comment by getnamo** [comment]
This embeds chromium into unreal so you can display a browser window in game in world etc as if you had a standard browser. Atm this packages for Windows platform only. See Unreal's WebBrowser plugin if you need wider support.

**Comment by RBoira97** [comment]
Alright, but this is not something i was looking for. Btw, thank you!
